<a href="https://colab.research.google.com/github/bah862696-coder/DI-Bootcamp/blob/master/Exercises_XP_Open_Source_LLMs_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises XP: Open-Source LLM Strategy (Student)
Use this guided notebook and fill each TODO. Run it in Colab if you prefer; GPU not required unless you try optional model runs.

## What you'll learn
- Identify degrees of openness in LLMs and what each enables.
- Understand and compare open-source licenses.
- Assess strengths/trade-offs of open LLMs for specific constraints (CPU, math, multilingual).
- Evaluate which models fit given hardware and licensing needs.
- Use open tools/leaderboards to guide model selection.
- Plan deployment trade-offs (local vs. cloud).

## What you will create
- Comparative LLM openness analysis (table + paragraph + healthcare prompt answer).
- Licensing compatibility checklist for SaaS products.
- Quiz-style reflection on LLM selection.
- Local deployment readiness checklist + upgrade notes.
- Benchmark-based model match guide.
- Hardware upgrade plan / cost-benefit comparison (local vs. cloud).

## Exercise 1: Open Source Levels Reflection
**Use:** Fully Open, Weights Released, Architecture Only; model components; fine-tuning/domain adaptation; healthcare compliance.

**Step-by-step**
1) Gather definitions for the three openness levels.  
2) Identify key characteristics (what is open; what you can/cannot do).  
3) Compare side by side in a table (what's open vs. impact).  
4) Write a 3?5 sentence comparative paragraph.  
5) Answer the healthcare prompt (1?2 sentences) about retraining on clinical data.

**Deliverables:** paragraph + healthcare answer.

In [1]:
import pandas as pd

# Exercise 1: Definitions and key characteristics
open_source_levels = {
    "Fully Open": {
        "definition": "Models where the training code, data cleaning scripts, and weights are all public (e.g., Pythia, OLMo).",
        "what_is_open": ["Training data recipes", "Model weights and code"],
        "what_you_can_do": ["Full audit of data bias", "Reproduce training from scratch"],
        "what_you_cannot_do": ["Hide proprietary data if contributing back to some copyleft projects"],
    },
    "Weights Released": {
        "definition": "Pre-trained weights are available, but the specific training data or exact pipeline might be private (e.g., Mistral, Llama).",
        "what_is_open": ["Model weights", "Inference code"],
        "what_you_can_do": ["Fine-tune on private data", "Self-host locally"],
        "what_you_cannot_do": ["Know exactly which documents were in the training set"],
    },
    "Architecture Only": {
        "definition": "Only the paper or the structural design is public; weights must be purchased or accessed via API (common in research papers before release).",
        "what_is_open": ["Model layers/parameters count", "Attention mechanism details"],
        "what_you_can_do": ["Implement the structure in code", "Study the theoretical efficiency"],
        "what_you_cannot_do": ["Generate text without training it yourself first"],
    },
}
display(pd.DataFrame(open_source_levels).T)

,definition,what_is_open,what_you_can_do,what_you_cannot_do
Fully Open,"Models where the training code, data cleaning ...","[Training data recipes, Model weights and code]","[Full audit of data bias, Reproduce training f...",[Hide proprietary data if contributing back to...
Weights Released,"Pre-trained weights are available, but the spe...","[Model weights, Inference code]","[Fine-tune on private data, Self-host locally]",[Know exactly which documents were in the trai...
Architecture Only,Only the paper or the structural design is pub...,"[Model layers/parameters count, Attention mech...","[Implement the structure in code, Study the th...",[Generate text without training it yourself fi...

In [2]:
comparison_table = """| Openness level | What's open? | Impact on retraining/modifying |
| --- | --- | --- |
| Fully Open | Code, weights, and data info | Highest: Allows deep domain adaptation and bias auditing. |
| Weights Released | Model weights and config | High: Perfect for fine-tuning (SFT/LoRA) on private datasets. |
| Architecture Only | Design patterns | Low: Requires massive compute to actually use/train from zero. |"""
print(comparison_table)

| Openness level | What's open? | Impact on retraining/modifying |
| --- | --- | --- |
| Fully Open | Code, weights, and data info | Highest: Allows deep domain adaptation and bias auditing. |
| Weights Released | Model weights and config | High: Perfect for fine-tuning (SFT/LoRA) on private datasets. |
| Architecture Only | Design patterns | Low: Requires massive compute to actually use/train from zero. |

In [3]:
comparative_paragraph = """The three levels of openness represent a spectrum of transparency and control for developers. Fully open models provide the ultimate visibility for security-sensitive sectors, whereas weights-released models offer a pragmatic middle ground for commercial deployment. Architecture-only releases primarily benefit the research community by advancing structural innovation without necessarily providing a ready-to-use tool. Choosing between them depends on whether you need to audit the training data or simply apply the model to a new task."""
print(comparative_paragraph)

The three levels of openness represent a spectrum of transparency and control for developers. Fully open models provide the ultimate visibility for security-sensitive sectors, whereas weights-released models offer a pragmatic middle ground for commercial deployment. Architecture-only releases primarily benefit the research community by advancing structural innovation without necessarily providing a ready-to-use tool. Choosing between them depends on whether you need to audit the training data or simply apply the model to a new task.

In [4]:
healthcare_prompt_answer = """For retraining a model on sensitive clinical data, a 'Weights Released' or 'Fully Open' model is essential. This allows the model to be hosted on-premise to ensure HIPAA compliance while enabling fine-tuning to learn specific medical terminology."""
print(healthcare_prompt_answer)

For retraining a model on sensitive clinical data, a 'Weights Released' or 'Fully Open' model is essential. This allows the model to be hosted on-premise to ensure HIPAA compliance while enabling fine-tuning to learn specific medical terminology.

## Exercise 2: License Check for SaaS Use
**Use:** HF model pages; permissive vs. copyleft; commercial clauses; restrictions (MAU caps, attribution, export controls).

**Step-by-step**
1) Select two HF models (e.g., Mistral-7B-Instruct, Llama-2-7b-chat-hf) and note URLs.  
2) Locate the License field and copy the name.  
3) Determine if commercial use is allowed/restricted/prohibited; note conditions.  
4) Identify extra restrictions (MAU caps, attribution, export/geography).  
5) Build the markdown checklist with your findings.

**Deliverables:** model names + URLs + completed checklist.

In [5]:
license_checklist = [
    {
        "model": "mistralai/Mistral-7B-Instruct-v0.3",
        "url": "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
        "license": "Apache 2.0",
        "commercial_use": "Yes",
        "restrictions": ["None (Permissive)", "Attribution required"],
    },
    {
        "model": "meta-llama/Llama-2-7b-chat-hf",
        "url": "https://huggingface.co/meta-llama/Llama-2-7b-chat-hf",
        "license": "Llama 2 Community License",
        "commercial_use": "Conditional",
        "restrictions": ["MAU cap (700M+ requires special license)", "No use to improve other models"],
    },
]
display(pd.DataFrame(license_checklist))

,model,url,license,commercial_use,restrictions
0,mistralai/Mistral-7B-Instruct-v0.3,https://huggingface.co/mistralai/Mistral-7B-In...,Apache 2.0,Yes,"[None (Permissive), Attribution required]"
1,meta-llama/Llama-2-7b-chat-hf,https://huggingface.co/meta-llama/Llama-2-7b-c...,Llama 2 Community License,Conditional,"[MAU cap (700M+ requires special license), No ..."

### Checklist template (fill and keep in markdown)
- [ ] **Model 1**  
  - Type of license:  
    - [ ] License name  
  - Commercial use allowed:  
    - [ ] Yes / No / Conditional  
  - Restrictions:  
    - [ ] Restriction #1  
    - [ ] Restriction #2
- [ ] **Model 2**  
  - Type of license:  
    - [ ] License name  
  - Commercial use allowed:  
    - [ ] Yes / No / Conditional  
  - Restrictions:  
    - [ ] Restriction #1  
    - [ ] Restriction #2

## Exercise 3: LLM Matchmaker Challenge
**Use:** CPU inference, low-end laptops, multilingual needs; HF filters; size <=7B; benchmarks (BoolQ, GSM8K, FLORES-200).

**Step-by-step**
1) Analyze team needs (LegalTech CPU logic; EdTech math/logic low-end; Global NGO multilingual >=5 langs).  
2) Apply HF filters (cpu/quantized, logic/math/multilingual tags, size <=7B).  
3) List 3?5 candidates per team with params/arch/quantization/benchmarks.  
4) Compare top 2 per team and pick the best model with justification.  
5) Fill the table with your picks.

**Deliverables:** filter summary + filled picks table.

In [6]:
filters_by_team = {
    "LegalTech": ["text-generation", "gguf", "logic", "boolq", "size <= 7B"],
    "EdTech": ["math", "gsm8k", "4-bit", "q4_k_m", "size <= 3B"],
    "Global NGO": ["multilingual", "flores-200", "m2m100", "size <= 7B"],
}
print(filters_by_team)

{'LegalTech': ['text-generation', 'gguf', 'logic', 'boolq', 'size <= 7B'], 'EdTech': ['math', 'gsm8k', '4-bit', 'q4_k_m', 'size <= 3B'], 'Global NGO': ['multilingual', 'flores-200', 'm2m100', 'size <= 7B']}

In [7]:
candidates_by_team = {
    "LegalTech": [
        {"model": "Mistral-7B-v0.3-GGUF", "params_b": "7B", "arch": "Mistral", "optimization": "Q4_K_M", "benchmarks": "High BoolQ"},
        {"model": "Phi-3-mini-4k-instruct", "params_b": "3.8B", "arch": "Phi", "optimization": "GGUF", "benchmarks": "Strong logic"},
    ],
    "EdTech": [
        {"model": "Qwen2.5-Math-1.5B", "params_b": "1.5B", "arch": "Qwen", "optimization": "INT4", "benchmarks": "High GSM8K"},
        {"model": "Llama-3.2-1B", "params_b": "1B", "arch": "Llama", "optimization": "Q4_0", "benchmarks": "Efficient"},
    ],
    "Global NGO": [
        {"model": "Aya-23-8B", "params_b": "8B", "arch": "T5-style", "optimization": "Quantized", "benchmarks": "Multilingual SOTA"},
        {"model": "BLOOM-7B1", "params_b": "7.1B", "arch": "BLOOM", "optimization": "GGUF", "benchmarks": "Wide lang support"},
    ],
}
display(candidates_by_team)

{'LegalTech': [{'model': 'Mistral-7B-v0.3-GGUF',
   'params_b': '7B',
   'arch': 'Mistral',
   'optimization': 'Q4_K_M',
   'benchmarks': 'High BoolQ'},
  {'model': 'Phi-3-mini-4k-instruct',
   'params_b': '3.8B',
   'arch': 'Phi',
   'optimization': 'GGUF',
   'benchmarks': 'Strong logic'}],
 'EdTech': [{'model': 'Qwen2.5-Math-1.5B',
   'params_b': '1.5B',
   'arch': 'Qwen',
   'optimization': 'INT4',
   'benchmarks': 'High GSM8K'},
  {'model': 'Llama-3.2-1B',
   'params_b': '1B',
   'arch': 'Llama',
   'optimization': 'Q4_0',
   'benchmarks': 'Efficient'}],
 'Global NGO': [{'model': 'Aya-23-8B',
   'params_b': '8B',
   'arch': 'T5-style',
   'optimization': 'Quantized',
   'benchmarks': 'Multilingual SOTA'},
  {'model': 'BLOOM-7B1',
   'params_b': '7.1B',
   'arch': 'BLOOM',
   'optimization': 'GGUF',
   'benchmarks': 'Wide lang support'}]}

In [8]:
matchmaker_table = """| Team | Needs | Your Pick |
| --- | --- | --- |
| LegalTech | Fast logic-heavy CPU | Phi-3-mini-4k (GGUF) - Extremely efficient for its size on CPU. |
| EdTech | Math/Logic on low-end | Qwen2.5-Math-1.5B - Best math performance per parameter count. |
| Global NGO | 5+ Languages | Aya-23-8B - Cohere's dedicated multilingual powerhouse. |"""
print(matchmaker_table)

| Team | Needs | Your Pick |
| --- | --- | --- |
| LegalTech | Fast logic-heavy CPU | Phi-3-mini-4k (GGUF) - Extremely efficient for its size on CPU. |
| EdTech | Math/Logic on low-end | Qwen2.5-Math-1.5B - Best math performance per parameter count. |
| Global NGO | 5+ Languages | Aya-23-8B - Cohere's dedicated multilingual powerhouse. |

## Exercise 4: Local Readiness Audit
**Use:** RAM/disk/OS; llama.cpp requirements (AVX/SSE, cmake/make/gcc/clang); quantized formats (GGUF).

**Step-by-step**
1) Gather system specs (RAM, free disk, OS type/version).  
2) Fill the audit table and mark ?/?.  
3) Check llama.cpp readiness (instruction sets, compilers, build tools).  
4) Identify upgrade needs for each ?.

**Deliverables:** filled table + upgrade summary.

In [9]:
system_specs = {
    "ram_gb": "12 GB",
    "free_disk_gb": "25 GB",
    "os": "Windows 11 (WSL2)",
}
print(system_specs)

{'ram_gb': '12 GB', 'free_disk_gb': '25 GB', 'os': 'Windows 11 (WSL2)'}

In [10]:
readiness_table = """| Requirement | Your System Specs | Meets Requirement? |
| --- | --- | --- |
| RAM (>= 16 GB) | 12 GB | ❌ |
| Free Disk Space (>= 40 GB) | 25 GB | ❌ |
| OS (Linux/WSL2) | WSL2 | ✅ |"""
print(readiness_table)

| Requirement | Your System Specs | Meets Requirement? |
| --- | --- | --- |
| RAM (>= 16 GB) | 12 GB | ❌ |
| Free Disk Space (>= 40 GB) | 25 GB | ❌ |
| OS (Linux/WSL2) | WSL2 | ✅ |

In [11]:
llama_cpp_readiness = {
    "cpu_instruction_support": "AVX2",
    "tooling": ["cmake 3.20", "gcc 11.4"],
    "other_requirements": "Build-essential package needed on WSL",
}
print(llama_cpp_readiness)

{'cpu_instruction_support': 'AVX2', 'tooling': ['cmake 3.20', 'gcc 11.4'], 'other_requirements': 'Build-essential package needed on WSL'}

In [12]:
upgrade_actions = [
    "Increase RAM to 16GB or 32GB for smoother 7B/13B inference.",
    "Clear 20GB of disk space to accommodate GGUF models and build files."
]
print(upgrade_actions)

['Increase RAM to 16GB or 32GB for smoother 7B/13B inference.', 'Clear 20GB of disk space to accommodate GGUF models and build files.']

## Exercise 5: Benchmark-Based Model Explorer
**Use:** Open LLM Leaderboard; HellaSwag and MMLU scores; license types; use-case mapping.

**Step-by-step**
1) Pick three models from the leaderboard with different strengths (high HellaSwag, high MMLU, balanced).  
2) Record HellaSwag, MMLU, license, and ideal use case.  
3) Fill the comparison table.  
4) Optional: 1?2 sentence reflection on why benchmarks matter.  
5) Quiz-style reflection: write 3 short Q&A items about choosing models for different constraints.

**Deliverables:** model list + filled table + quiz-style reflection (+ optional reflection paragraph).

In [13]:
leaderboard_models = [
    {"model": "Llama-3.1-8B-Instruct", "url": "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct", "hellaswag": "83.1", "mmlu": "68.4", "license": "Llama 3.1", "ideal_use_case": "General Assistant"},
    {"model": "Mistral-7B-v0.3", "url": "https://huggingface.co/mistralai/Mistral-7B-v0.3", "hellaswag": "81.5", "mmlu": "61.2", "license": "Apache 2.0", "ideal_use_case": "Commercial Chatbots"},
    {"model": "Qwen2.5-7B-Instruct", "url": "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct", "hellaswag": "84.8", "mmlu": "74.1", "license": "Apache 2.0", "ideal_use_case": "Coding & Math"},
]
display(pd.DataFrame(leaderboard_models))

,model,url,hellaswag,mmlu,license,ideal_use_case
0,Llama-3.1-8B-Instruct,https://huggingface.co/meta-llama/Llama-3.1-8B...,83.1,68.4,Llama 3.1,General Assistant
1,Mistral-7B-v0.3,https://huggingface.co/mistralai/Mistral-7B-v0.3,81.5,61.2,Apache 2.0,Commercial Chatbots
2,Qwen2.5-7B-Instruct,https://huggingface.co/Qwen/Qwen2.5-7B-Instruct,84.8,74.1,Apache 2.0,Coding & Math

In [14]:
benchmark_table = """| Model Name | HellaSwag Score | MMLU Score | License Type | Ideal Use Case |
| --- | --- | --- | --- | --- |
| Llama-3.1-8B | 83.1 | 68.4 | Llama 3.1 | General high-performance bot |
| Mistral-7B-v0.3 | 81.5 | 61.2 | Apache 2.0 | Unrestricted commercial use |
| Qwen2.5-7B | 84.8 | 74.1 | Apache 2.0 | Technical tasks & Reasoning |"""
print(benchmark_table)

| Model Name | HellaSwag Score | MMLU Score | License Type | Ideal Use Case |
| --- | --- | --- | --- | --- |
| Llama-3.1-8B | 83.1 | 68.4 | Llama 3.1 | General high-performance bot |
| Mistral-7B-v0.3 | 81.5 | 61.2 | Apache 2.0 | Unrestricted commercial use |
| Qwen2.5-7B | 84.8 | 74.1 | Apache 2.0 | Technical tasks & Reasoning |

### Optional reflection
1?2 sentences on why benchmarks?not hype?should guide model choice.

In [15]:
quiz_reflection = [
    {"question": "Why use a GGUF format for local deployment?", "answer": "It allows efficient CPU inference and memory mapping for consumer hardware."},
    {"question": "What license is best for a SaaS startup?", "answer": "Apache 2.0 or MIT are preferred due to lack of commercial restrictions."},
    {"question": "How do benchmarks help in model selection?", "answer": "They provide objective data on reasoning vs. knowledge to match the model to the task."},
]
display(pd.DataFrame(quiz_reflection))

,question,answer
0,Why use a GGUF format for local deployment?,It allows efficient CPU inference and memory m...
1,What license is best for a SaaS startup?,Apache 2.0 or MIT are preferred due to lack of...
2,How do benchmarks help in model selection?,They provide objective data on reasoning vs. k...

## Exercise 6: Cloud vs. Local Deployment Plan
**Use:** local vs. cloud cost/latency/scalability/security/maintenance; optional Colab timing.

**Step-by-step**
1) Draft 5 bullets pairing local vs. cloud pros/cons.  
2) Optional: run a 7B model on Colab; note model and response time.  
3) Summarize Colab observation if you ran it.

**Deliverables:** 5 bullets; optional Colab report (model + time).

In [16]:
pros_and_cons = [
    "Local: Zero operational cost per token vs. Cloud: Pay-as-you-go flexibility.",
    "Local: Data never leaves your hardware (Security) vs. Cloud: Data transit risks.",
    "Local: Limited by your own GPU/RAM vs. Cloud: Scale to multiple A100s instantly.",
    "Local: High initial hardware investment vs. Cloud: No upfront hardware costs.",
    "Local: Maintenance and cooling are your responsibility vs. Cloud: Managed infrastructure.",
]
print("\n".join(pros_and_cons))

Local: Zero operational cost per token vs. Cloud: Pay-as-you-go flexibility.
Local: Data never leaves your hardware (Security) vs. Cloud: Data transit risks.
Local: Limited by your own GPU/RAM vs. Cloud: Scale to multiple A100s instantly.
Local: High initial hardware investment vs. Cloud: No upfront hardware costs.
Local: Maintenance and cooling are your responsibility vs. Cloud: Managed infrastructure.

In [17]:
colab_run = {
    "model_tested": "Llama-3.2-3B-Instruct (4-bit)",
    "response_time_seconds": "~1.2s",
    "notes": "Fast response on T4 GPU; memory usage was minimal.",
}
print(colab_run)

{'model_tested': 'Llama-3.2-3B-Instruct (4-bit)', 'response_time_seconds': '~1.2s', 'notes': 'Fast response on T4 GPU; memory usage was minimal.'}